### ISSUE TITLE
Query parameters are not redirected

### ISSUE THREAD

**Issue by michael-evelt-lvm** [ibmix-berlin/magnolia-vanity-url#26]
First of all: Thank you for this module! I really like it.

Considering the issue:
Apperently when using a 301 redirct any query parameters are dropped. Example from our website:
![image](https://github.com/ibmix-berlin/magnolia-vanity-url/assets/47484454/63c1bed3-adad-404e-93b0-59958e89167d)

If the URL is called using a query parameter (/agentur-ausbildung?dbaNr=1234) the redirect is working fine, but the original query parameter is lost. Since the parameter is optional and the value varies, the Link Suffix field would not fix this for us.

To us it would be the preferred behaviour if all query parameters could be passed on to the redirct uri. If this is not desired for all cases, a checkbox could be handy to enable or disable this behaviour.

Thank you very much and best wishes!

**Comment by serialcool** [comment]
Hi,
thx, I will look at this feature request and I think it should be possible to implement the support for this.

For your information with version 1.6.1 the module was moved to a new GitHub space and the Maven coords changed, too.
`<dependency>
    <artifactId>magkit-vanity-url</artifactId>
    <groupId>de.ibmix.magkit</groupId>
    <version>1.6.0</version>
</dependency>`

**Comment by serialcool** [comment]
I released version 1.6.1 in the new GitHub project. Please test your issue and reopen, if it shouldn't work for you.

**Comment by michael-evelt-lvm** [comment]
Thank you very much for taking the time!

Unfortnately, it seems, that I cannot access the new version in the new space via a maven build. Also the nexus here does not seem to contain any entries:
https://nexus.magnolia-cms.com/#nexus-search;quick~magkit-vanity-url

Any idea why this is happening?

**Comment by serialcool** [comment]
I see the new artefact at https://nexus.magnolia-cms.com/#browse/browse:magnolia.forge.releases:de%2Fibmix%2Fmagkit%2Fmagkit-vanity-url%2F1.6.1 on Magnolias Nexus.

**Comment by michael-evelt-lvm** [comment]
Oh sorry, you are right, I only changed the dependency management entry and not the actual dependency ...

**Comment by michael-evelt-lvm** [comment]
So, I just tested it and it seems to be working very well! Thanks again!
